export const questQuestions=[
 {id:'ana-capture',caseId:'ana',stage:'Capture',prompt:'Two records identify the same fictional person differently. What should happen first?',options:['Verify identity against the source record and resolve the mismatch with an auditable correction.','Choose the most recent record and send immediately.','Create a third record to avoid delay.'],explanation:'Verify the right record while context is available, then make a traceable correction.'},
 {id:'ana-check',caseId:'ana',stage:'Check',prompt:'A referral says only “Please assess.” What repair best helps the receiving team?',options:['Attach every record the originating unit holds.','Send the short message and wait for questions.','Add reason, urgency, relevant summary, requested service, and a response route.'],explanation:'A concise, purposeful referral gives the next team enough context to act.'},
 {id:'ana-protect',caseId:'ana',stage:'Protect',prompt:'A colleague suggests posting the referral in an open group chat. What is the safer route?',options:['Post the full record and delete it after acknowledgment.','Use the designated referral channel with access limited to the responsible team.','Do not share anything, even through the approved channel.'],explanation:'Use an accountable route with access limited to people responsible for the handoff.'},
 {id:'ana-exchange',caseId:'ana',stage:'Exchange',prompt:'What indicates that a referral actually reached the intended service?',options:['A “sent” icon on the originating screen.','An acknowledgment with status and a route for follow-up.','A copy in a spreadsheet with no receiving status.'],explanation:'Sending is different from receiving and acting; acknowledgment gives the origin a known state.'},
 {id:'ana-return',caseId:'ana',stage:'Return',prompt:'What closes the information loop after the receiving service completes the encounter?',options:['Keep the outcome only at the receiving facility.','Return status, relevant outcome, and follow-up responsibility to the originating team.','Wait for the person to repeat the full story at the next visit.'],explanation:'The originating team needs the outcome and next responsibility to continue the journey.'},
 {id:'ana-use',caseId:'ana',stage:'Use',prompt:'Several referrals lack receiving status. What is the most useful management response?',options:['Publish the names of people with missing status.','Compare sent and acknowledged counts, assign an owner, and review the gap.','Report only the total sent and ignore missing responses.'],explanation:'Turn routine aggregate data into a specific workflow improvement and a measure.'},
 {id:'redirect-capture',caseId:'redirect',stage:'Capture',prompt:'Two service labels describe the same requested assessment. Where should the team start?',options:['Check the shared local definition and correct the ambiguous label.','Keep both labels and hope the receiver interprets them.','Delete the service field.'],explanation:'Agree on meaning before routing so the next team can understand the request.'},
 {id:'redirect-check',caseId:'redirect',stage:'Check',prompt:'What should accompany a request being routed to another service?',options:['The entire clinic archive, just in case.','Only a first name and “please advise.”','Verified identity reference, reason, urgency, relevant summary, and response route.'],explanation:'Send the relevant minimum needed for the receiving team to act.'},
 {id:'redirect-protect',caseId:'redirect',stage:'Protect',prompt:'The coordinator is away. Who should see the request?',options:['Everyone in the regional staff mailing list.','The authorized backup coordinator through the approved queue.','Nobody until the coordinator returns.'],explanation:'A documented backup role supports continuity with controlled access.'},
 {id:'redirect-exchange',caseId:'redirect',stage:'Exchange',prompt:'The first facility cannot accept the request. What status must the origin receive?',options:['Mark “sent” again without a destination or owner.','Redirected, with reason, new destination, and named responsible team.','Delete the first request and start over without history.'],explanation:'A redirect is useful when the new route and responsibility remain visible.'},
 {id:'redirect-return',caseId:'redirect',stage:'Return',prompt:'The second service accepts the request. What should the originating clinic see?',options:['Acceptance and next-step details in the authorized clinic workflow.','Only the first facility’s redirect notice.','Nothing until a quarterly report arrives.'],explanation:'The originating team needs enough status to coordinate the next step.'},
 {id:'redirect-use',caseId:'redirect',stage:'Use',prompt:'Redirects rise across the network. What should managers investigate first?',options:['Call every redirect a staff error.','Compare reasons and destinations, then review definitions and capacity with owners.','Hide redirects from the monthly report.'],explanation:'Use aggregate patterns to form a testable operational question before assigning blame.'},
 {id:'manager-capture',caseId:'manager',stage:'Capture',prompt:'The EMR count is lower than the facility log. What is the first data-quality question?',options:['Where in the workflow are records captured differently or missed?','The EMR proves the lower count is correct.','Replace the facility log with the EMR count immediately.'],explanation:'Locate the capture gap before choosing which source to trust.'},
 {id:'manager-check',caseId:'manager',stage:'Check',prompt:'How should a manager compare two conflicting activity counts?',options:['Define each measure, period, source, and denominator before comparing totals.','Use the larger number because it shows more service.','Average the numbers and publish the result.'],explanation:'Comparable definitions and denominators are needed before interpreting a difference.'},
 {id:'manager-protect',caseId:'manager',stage:'Protect',prompt:'A dashboard review needs detail about missing entries. What is the appropriate access?',options:['Post identifiable examples in a public dashboard.','Use authorized worklists and aggregate views, limiting identifiable detail to the responsible team.','Copy every record into a shared spreadsheet.'],explanation:'Investigate gaps with the least identifiable detail and the right access.'},
 {id:'manager-exchange',caseId:'manager',stage:'Exchange',prompt:'A facility discovers a reconciliation gap. What should it send to the program team?',options:['A screenshot with no definitions or date.','A defined aggregate gap, period, owner, and action status through the approved route.','Only the headline count that looks best.'],explanation:'A useful management handoff makes the measure, period, responsibility, and action visible.'},
 {id:'manager-return',caseId:'manager',stage:'Return',prompt:'The EMR queue stalls during connectivity loss. What should return to frontline staff?',options:['A documented downtime and reconciliation process with an owner and gap review.','A reminder to enter everything again without checking duplicates.','No feedback until the annual review.'],explanation:'Feedback should give staff a repair process, owner, and way to see whether it worked.'},
 {id:'manager-use',caseId:'manager',stage:'Use',prompt:'What is the strongest measure for improving incomplete activity capture?',options:['Track only the largest monthly headline.','Track reconciled totals and exceptions over time against a defined denominator.','Stop reporting the facility log.'],explanation:'A repeated measure with a denominator shows whether capture improves and where exceptions remain.'},
 {id:'synthesis-identity',caseId:'synthesis',stage:'Identity',prompt:'Which sequence best protects continuity at the beginning of a referral?',options:['Verify identity, correct the source record, then create the purposeful referral.','Create a new record, send quickly, and reconcile later.','Send the full archive so the receiver can decide.'],explanation:'Reliable identity comes before purposeful, minimum-necessary exchange.'},
 {id:'synthesis-minimum',caseId:'synthesis',stage:'Context',prompt:'What makes a referral packet useful without becoming excessive?',options:['Relevant purpose, urgency, summary, requested service, and response route.','Everything available in the originating chart.','Only a name and a request to call back.'],explanation:'Use the relevant minimum that lets the next team act and respond.'},
 {id:'synthesis-governed',caseId:'synthesis',stage:'Governance',prompt:'What makes an information exchange accountable?',options:['A broad channel where someone may notice it.','An authorized channel, intended recipient, status, and follow-up responsibility.','A local copy with no receiving confirmation.'],explanation:'Accountability connects protection with a known recipient and a visible next action.'},
 {id:'synthesis-ack',caseId:'synthesis',stage:'Acknowledgment',prompt:'Why is an acknowledgment different from a sent status?',options:['It confirms the receiving service has a known state and route for next action.','It is only a duplicate of the originating record.','It proves the person’s care is complete.'],explanation:'Acknowledgment confirms a handoff state; it does not by itself mean the journey is complete.'},
 {id:'synthesis-return',caseId:'synthesis',stage:'Return',prompt:'What should come back so the originating team can continue its work?',options:['Only the original request text.','Relevant outcome, current status, follow-up owner, and next action.','A quarterly total without case status.'],explanation:'The loop returns useful action, not merely a copy or an aggregate headline.'},
 {id:'synthesis-use',caseId:'synthesis',stage:'Management',prompt:'What turns routine information into a service improvement?',options:['A larger dashboard with more unverified numbers.','A defined measure, accountable owner, review date, and action on the gap.','A public list of people connected to missing data.'],explanation:'Management use connects a trustworthy measure to an owner, action, and review.'}
];

export function selectQuestQuestions(length){
 const byCase=id=>questQuestions.filter(q=>q.caseId===id);
 const shuffle=list=>[...list].sort(()=>Math.random()-.5);
 const base=['ana','redirect','manager'].flatMap(id=>shuffle(byCase(id)).slice(0,Math.max(2,Math.floor(length/6))));
 const remaining=shuffle(questQuestions.filter(q=>!base.includes(q))).slice(0,Math.max(0,length-base.length));
 return shuffle([...base,...remaining]).slice(0,length).map(q=>q.id);
}
