import {questQuestions} from './quest-bank.js';

const config=globalThis.__SUPABASE_CONFIG__;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const findQuestion=id=>questQuestions.find(q=>q.id===id);
const asMillis=value=>typeof value==='number'?value:(Date.parse(value||'')||0);

export async function mountTeamQuest({root,onBack}){
 const state={role:null,sessionId:null,playerId:null,mode:null,session:null,scorecard:null,error:'',timer:null,supabase:null,channel:null,answeredQuestionIds:new Set()};
 const showError=error=>{state.error=error?.message||String(error||'Something went wrong.');render()};
 function shell(content){root.innerHTML=`<section class="quest-shell"><div class="quest-top"><button class="back-button" data-action="quest-back">â† <span>Modes</span></button><div><p class="eyebrow">LIVE ROOM / TEAM QUEST</p><h1>Keep the story moving.</h1></div><span class="quest-badge">EDUCATIONAL SESSION</span></div>${state.error?`<p class="quest-error" role="alert">${esc(state.error)}</p>`:''}${content}</section>`}
 function renderLanding(){shell(`<div class="quest-grid"><section class="quest-card"><p class="eyebrow">HOST A SESSION</p><h2>Create a room</h2><p>Choose a scoring mode and question length, then share the six-character code.</p><label>Scoring mode<select id="questMode"><option value="individual">Individual players</option><option value="team">Teams</option></select></label><label>Quest length<select id="questLength"><option value="6">6 questions · quick round</option><option value="12">12 questions · standard round</option><option value="18">18 questions · full quest</option></select></label><button class="primary" data-action="quest-create">Create room →</button></section><section class="quest-card"><p class="eyebrow">JOIN A SESSION</p><h2>Enter a room</h2><p>Use the code shown by the facilitator. You will receive a generated player ID.</p><label>Room code<input id="questCode" maxlength="6" autocomplete="off" placeholder="ABC123"></label><label>Team name <span class="small">optional in Team mode</span><input id="questTeam" maxlength="32" autocomplete="off" placeholder="e.g. Green team"></label><button class="secondary" data-action="quest-join">Join room →</button></section></div><div class="quest-note"><strong>No personal profile required.</strong> Anonymous Supabase authentication creates a session-scoped player label. Do not enter patient data or personal information.</div>`)}
 function renderLobby(){const players=state.session?.players||[];shell(`<div class="quest-lobby"><div class="room-code"><span>ROOM CODE</span><strong>${esc(state.session.roomCode)}</strong><p>Share this code with the room.</p></div><div class="lobby-card"><p class="eyebrow">${state.role==='host'?'HOST LOBBY':'WAITING ROOM'}</p><h2>${state.role==='host'?'Players are joining':'You are in the room'}</h2><p>${state.role==='host'?'Start when the room is ready.':'The host will start the first question.'}</p><div class="player-list">${players.length?players.map(p=>`<span>${esc(p.playerId)}${p.teamName?` · ${esc(p.teamName)}`:''}</span>`).join(''):'No players yet.'}</div>${state.role==='host'?`<button class="primary" data-action="quest-start" ${players.length?'':'disabled'}>Start quest →</button>`:`<p class="quest-player-label">Your label: <strong>${esc(state.playerId)}</strong></p>`}</div></div>`)}
 function renderQuestion(){const s=state.session;const q=findQuestion(s.questionIds[s.currentIndex]);if(!q)return shell('<p class="quest-error">Question data is unavailable.</p>');const reveal=s.status==='reveal';const answered=state.answeredQuestionIds.has(q.id);clearInterval(state.timer);if(!reveal&&s.questionDeadlineAt){state.timer=setInterval(()=>{const el=root.querySelector('#questTimer');if(el)el.textContent=`${Math.max(0,Math.ceil((s.questionDeadlineAt-Date.now())/1000))}s`;},250)}shell(`<div class="quest-progress"><span>QUESTION ${s.currentIndex+1} / ${s.questionIds.length}</span><span class="quest-timer" id="questTimer">${reveal?'REVEALED':`${Math.max(0,Math.ceil((s.questionDeadlineAt-Date.now())/1000))}s`}</span></div><div class="quest-question"><p class="eyebrow">${esc(q.stage)}</p><h2>${esc(q.prompt)}</h2><div class="quest-options">${q.options.map((option,index)=>`<button class="quest-option ${reveal&&s.reveal?.correctIndex===index?'correct':''}" data-action="quest-answer" data-option="${index}" ${state.role==='host'||reveal||answered?'disabled':''}><span>${'ABC'[index]}</span>${esc(option)}</button>`).join('')}</div>${answered&&!reveal?'<p class="quest-wait">Answer locked. Wait for the host to reveal the explanation.</p>':''}${reveal?`<div class="quest-reveal"><strong>Preferred route: ${'ABC'[s.reveal.correctIndex]}</strong><p>${esc(s.reveal.explanation)}</p></div>`:''}</div><div class="quest-controls">${state.role==='host'&&!reveal?`<button class="primary" data-action="quest-reveal">Reveal answer</button><button class="quiet" data-action="quest-end">End session</button>`:''}${state.role==='host'&&reveal?`<button class="primary" data-action="quest-next">${s.currentIndex===s.questionIds.length-1?'Finish quest':'Next question'} →</button><button class="quiet" data-action="quest-end">End session</button>`:''}<span class="small">${state.role==='host'?`${state.session.players.length} participant(s) in room.`:'Your answer is scored on correctness and response time.'}</span></div>`)}
 function renderScorecard(){const card=state.scorecard||state.session.scorecard||{individual:[],teams:[],indicators:[],note:''};const rows=state.mode==='team'?card.teams:card.individual;clearInterval(state.timer);shell(`<div class="scorecard"><p class="eyebrow">QUEST COMPLETE</p><h2>The room kept the story moving.</h2><p class="lead">${esc(card.note||'Educational feedback only.')}</p><div class="score-indicators">${(card.indicators||[]).map(item=>`<div><span>${esc(item.label)}</span><strong>${esc(item.status)}</strong></div>`).join('')}</div><div class="score-list">${rows.map((row,index)=>`<div class="score-row"><span class="rank">${index+1}</span><div><strong>${esc(row.teamName||row.playerId)}</strong><small>${row.accuracy}% accuracy · ${row.averageResponseMs}ms average${row.members?` · ${row.members} player(s)`:''}${row.participation?` · ${row.participation} answered`:''}</small></div><b>${row.score}</b></div>`).join('')}</div><div class="score-actions"><button class="primary" data-action="quest-print">Print scorecard</button><button class="quiet" data-action="quest-back">Return to modes</button></div></div>`)}
 function render(){if(!state.session)return renderLanding();if(state.session.status==='lobby')return renderLobby();if(state.session.status==='complete')return renderScorecard();return renderQuestion()}
 async function setup(){if(!config?.url||!config?.anonKey){state.error='Team Quest is not configured yet. Add the Supabase browser configuration to this deployment.';return renderLanding()}try{const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2.57.4?target=es2022');state.supabase=createClient(config.url,config.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});const {error}=await state.supabase.auth.signInAnonymously();if(error)throw error;renderLanding()}catch(error){showError(error)}}
 async function call(action,data={}){const {data:result,error}=await state.supabase.functions.invoke('team-quest',{body:{action,...data}});if(error)throw error;if(result?.error)throw new Error(result.error);return result}
 async function refresh(){const result=await call('get',{sessionId:state.sessionId});if(!result.session){state.error='This room is no longer available.';state.session=null;return renderLanding()}state.session={...result.session,questionStartedAt:asMillis(result.session.questionStartedAt),questionDeadlineAt:asMillis(result.session.questionDeadlineAt)};state.scorecard=result.scorecard;state.playerId=result.playerId||state.playerId;state.answeredQuestionIds=new Set(result.answeredQuestionIds||[]);state.mode=state.session.mode;render()}
 function watchSession(){if(state.channel)state.supabase.removeChannel(state.channel);state.channel=state.supabase.channel(`team-quest-${state.sessionId}`).on('postgres_changes',{event:'*',schema:'public',table:'team_sessions',filter:`id=eq.${state.sessionId}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'team_players',filter:`session_id=eq.${state.sessionId}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'team_scorecards',filter:`session_id=eq.${state.sessionId}`},refresh).subscribe();refresh().catch(showError)}
 root.addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;state.error='';try{if(action==='quest-back'){clearInterval(state.timer);if(state.channel)state.supabase.removeChannel(state.channel);onBack();return}if(action==='quest-create'){state.role='host';const result=await call('create',{mode:root.querySelector('#questMode').value,length:Number(root.querySelector('#questLength').value)});state.sessionId=result.sessionId;watchSession();return}if(action==='quest-join'){const result=await call('join',{roomCode:root.querySelector('#questCode').value.trim().toUpperCase(),teamName:root.querySelector('#questTeam').value.trim()});state.role='player';state.sessionId=result.sessionId;state.playerId=result.playerId;state.mode=result.mode;watchSession();return}if(action==='quest-start'){await call('start',{sessionId:state.sessionId});return}if(action==='quest-reveal'){await call('reveal',{sessionId:state.sessionId});return}if(action==='quest-next'){await call('next',{sessionId:state.sessionId});return}if(action==='quest-end'){await call('end',{sessionId:state.sessionId});return}if(action==='quest-answer'){await call('submit',{sessionId:state.sessionId,optionIndex:Number(button.dataset.option)});await refresh();return}if(action==='quest-print')window.print()}catch(error){showError(error)}});
 await setup();
}
