import {initializeApp,getApps} from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js';
import {getAuth,signInAnonymously} from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js';
import {getDatabase,onValue,ref} from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-database.js';
import {getFunctions,httpsCallable} from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-functions.js';
import {firebaseConfig} from './firebase-config.js';
import {questQuestions,selectQuestQuestions} from './quest-bank.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const findQuestion=id=>questQuestions.find(q=>q.id===id);

export async function mountTeamQuest({root,onBack}){
 const state={role:null,sessionId:null,playerId:null,mode:null,session:null,error:'',answeredQuestion:null,timer:null,auth:null,db:null,functions:null};
 const showError=error=>{state.error=error?.message||String(error||'Something went wrong.');render()};
 function shell(content){root.innerHTML=`<section class="quest-shell"><div class="quest-top"><button class="back-button" data-action="quest-back">← <span>Modes</span></button><div><p class="eyebrow">LIVE ROOM / TEAM QUEST</p><h1>Keep the story moving.</h1></div><span class="quest-badge">EDUCATIONAL SESSION</span></div>${state.error?`<p class="quest-error" role="alert">${esc(state.error)}</p>`:''}${content}</section>`}
 function renderLanding(){shell(`<div class="quest-grid"><section class="quest-card"><p class="eyebrow">HOST A SESSION</p><h2>Create a room</h2><p>Choose a scoring mode and question length, then share the six-character code.</p><label>Scoring mode<select id="questMode"><option value="individual">Individual players</option><option value="team">Teams</option></select></label><label>Quest length<select id="questLength"><option value="6">6 questions · quick round</option><option value="12">12 questions · standard round</option><option value="18">18 questions · full quest</option></select></label><button class="primary" data-action="quest-create">Create room →</button></section><section class="quest-card"><p class="eyebrow">JOIN A SESSION</p><h2>Enter a room</h2><p>Use the code shown by the facilitator. You will receive a generated player ID.</p><label>Room code<input id="questCode" maxlength="6" autocomplete="off" placeholder="ABC123"></label><label>Team name <span class="small">optional in Team mode</span><input id="questTeam" maxlength="32" autocomplete="off" placeholder="e.g. Green team"></label><button class="secondary" data-action="quest-join">Join room →</button></section></div><div class="quest-note"><strong>No personal profile required.</strong> Anonymous authentication creates a session-scoped player label. Do not enter patient data or personal information.</div>`)}
 function renderLobby(){const players=Object.values(state.session?.players||{});shell(`<div class="quest-lobby"><div class="room-code"><span>ROOM CODE</span><strong>${esc(state.sessionId)}</strong><p>Share this code with the room.</p></div><div class="lobby-card"><p class="eyebrow">${state.role==='host'?'HOST LOBBY':'WAITING ROOM'}</p><h2>${state.role==='host'?'Players are joining':'You are in the room'}</h2><p>${state.role==='host'?'Start when the room is ready.':'The host will start the first question.'}</p><div class="player-list">${players.length?players.map(p=>`<span>${esc(p.playerId)}${p.teamName?` · ${esc(p.teamName)}`:''}</span>`).join(''):'No players yet.'}</div>${state.role==='host'?`<button class="primary" data-action="quest-start" ${players.length?'':'disabled'}>Start quest →</button>`:`<p class="quest-player-label">Your label: <strong>${esc(state.playerId)}</strong></p>`}</div></div>`)}
 function renderQuestion(){const s=state.session;const q=findQuestion(s.questionIds[s.currentIndex]);if(!q)return shell('<p class="quest-error">Question data is unavailable.</p>');const reveal=s.status==='reveal';const answered=state.answeredQuestion===q.id;clearInterval(state.timer);if(!reveal&&s.questionDeadlineAt){state.timer=setInterval(()=>{const el=root.querySelector('#questTimer');if(el)el.textContent=`${Math.max(0,Math.ceil((s.questionDeadlineAt-Date.now())/1000))}s`;},250)}shell(`<div class="quest-progress"><span>QUESTION ${s.currentIndex+1} / ${s.questionIds.length}</span><span class="quest-timer" id="questTimer">${reveal?'REVEALED':`${Math.max(0,Math.ceil((s.questionDeadlineAt-Date.now())/1000))}s`}</span></div><div class="quest-question"><p class="eyebrow">${esc(q.stage)}</p><h2>${esc(q.prompt)}</h2><div class="quest-options">${q.options.map((option,index)=>`<button class="quest-option ${reveal&&s.reveal?.correctIndex===index?'correct':''}" data-action="quest-answer" data-option="${index}" ${state.role==='host'||reveal||answered?'disabled':''}><span>${'ABC'[index]}</span>${esc(option)}</button>`).join('')}</div>${answered&&!reveal?'<p class="quest-wait">Answer locked. Wait for the host to reveal the explanation.</p>':''}${reveal?`<div class="quest-reveal"><strong>Preferred route: ${'ABC'[s.reveal.correctIndex]}</strong><p>${esc(s.reveal.explanation)}</p></div>`:''}</div><div class="quest-controls">${state.role==='host'&&!reveal?`<button class="primary" data-action="quest-reveal">Reveal answer</button><button class="quiet" data-action="quest-end">End session</button>`:''}${state.role==='host'&&reveal?`<button class="primary" data-action="quest-next">${s.currentIndex===s.questionIds.length-1?'Finish quest':'Next question'} →</button><button class="quiet" data-action="quest-end">End session</button>`:''}<span class="small">${state.role==='host'?`${Object.keys(s.players||{}).length} participant(s) in room.`:'Your answer is scored on correctness and response time.'}</span></div>`)}
 function renderScorecard(){const card=state.session.scorecard;const rows=state.mode==='team'?card.teams:card.individual;clearInterval(state.timer);shell(`<div class="scorecard"><p class="eyebrow">QUEST COMPLETE</p><h2>The room kept the story moving.</h2><p class="lead">${esc(card.note)}</p><div class="score-list">${rows.map((row,index)=>`<div class="score-row"><span class="rank">${index+1}</span><div><strong>${esc(row.teamName||row.playerId)}</strong><small>${row.accuracy}% accuracy · ${row.averageResponseMs}ms average${row.members?` · ${row.members} player(s)`:''}</small></div><b>${row.score}</b></div>`).join('')}</div><div class="score-actions"><button class="primary" data-action="quest-print">Print scorecard</button><button class="quiet" data-action="quest-back">Return to modes</button></div></div>`)}
 function render(){if(!state.session)return renderLanding();if(state.session.status==='lobby')return renderLobby();if(state.session.status==='complete')return renderScorecard();return renderQuestion()}
 async function setup(){if(!firebaseConfig){state.error='Team Quest is not configured yet. Add the Firebase web configuration to this deployment before creating a room.';return renderLanding()}try{const app=getApps().find(item=>item.name==='team-quest')||initializeApp(firebaseConfig,'team-quest');state.auth=getAuth(app);state.db=getDatabase(app);state.functions=getFunctions(app);await signInAnonymously(state.auth);renderLanding()}catch(error){showError(error)}}
 function watchSession(){onValue(ref(state.db,`sessions/${state.sessionId}`),snapshot=>{state.session=snapshot.val();if(!state.session){state.error='This room is no longer available.';state.sessionId=null;state.role=null;return renderLanding()}render()})}
 async function call(name,data){return httpsCallable(state.functions,name)(data)}
 root.addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;state.error='';try{if(action==='quest-back'){clearInterval(state.timer);onBack();return}if(action==='quest-create'){state.mode=root.querySelector('#questMode').value;const length=Number(root.querySelector('#questLength').value);const result=await call('createSession',{mode:state.mode,length,questionIds:selectQuestQuestions(length)});state.role='host';state.sessionId=result.data.sessionId;watchSession();return}if(action==='quest-join'){const sessionId=root.querySelector('#questCode').value.trim().toUpperCase();const teamName=root.querySelector('#questTeam').value.trim();const result=await call('joinSession',{sessionId,teamName});state.role='player';state.sessionId=result.data.sessionId;state.playerId=result.data.playerId;state.mode=result.data.mode;watchSession();return}if(action==='quest-start'){await call('startSession',{sessionId:state.sessionId});return}if(action==='quest-reveal'){await call('revealQuestion',{sessionId:state.sessionId});return}if(action==='quest-next'){await call('nextQuestion',{sessionId:state.sessionId});return}if(action==='quest-end'){await call('endSession',{sessionId:state.sessionId});return}if(action==='quest-answer'){const questionId=state.session.questionIds[state.session.currentIndex];await call('submitAnswer',{sessionId:state.sessionId,optionIndex:Number(button.dataset.option)});state.answeredQuestion=questionId;render();return}if(action==='quest-print'){window.print()}}catch(error){showError(error)}});
 await setup();
}
